services:
  web:
    build: .
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=200
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
